source 'https://rubygems.org'
gem 'sinatra', '1.3.5'
gem 'puma'
gem 'shotgun'
gem 'cucumber'
gem 'rspec'
gem 'capybara'
gem 'pg'
gem 'dm-core'
gem 'dm-timestamps' 
gem 'dm-postgres-adapter'
gem 'dm-migrations'
gem 'dm-types'
gem 'sinatra-flash', '0.3.0', :require => 'sinatra/flash'
gem 'warden', '1.2.1'
gem 'data_mapper', '1.2.0'
