source 'https://rubygems.org'
gem 'sinatra', '1.3.5'
gem 'puma'
gem 'haml'
gem 'shotgun'
gem 'cucumber'
gem 'rspec'
gem 'capybara'
gem 'pg'
gem 'sinatra_more' 
gem 'datamapper'
gem 'dm-core dm-timestamps' 
gem 'dm-sqlite-adapter' 
gem 'dm-migrations'
