---
- hosts: all
  tasks:

   - name: install all the required packages
     sudo: yes
     yum: name={{item}} state=present
     with_items:
        - ruby
        - ruby-devel
        - postgresql-server
        - postgresql-devel
        - curl
        - rubygem-bundler
        - rubygem-nokogiri
        - python-psycopg2
        - postgresql-contrib

  # Database
   - name: enable postgresql
     command: systemctl enable postgresql
     sudo: true

   - name: initialize postgresql
     command: /usr/bin/postgresql-setup initdb creates=/var/lib/pgsql/data/postgresql.conf
     sudo: true

   - name: start postgresql
     service: state=started name=postgresql
     sudo: true
     
   - name: create dev database
     postgresql_db: name=agile-fishbowl state=present user=postgres
     sudo_user: postgres
     sudo: true
   
#   - name: set username and password for database
#     postgresql_user: db=agile-fishbowl name=twer password=Thought01 priv=ALL state=present role_attr_flags=CREATEDB,SUPERUSER,LOGIN
#     sudo_user: postgres
#     sudo: true













